name: Build & Test
description: "Builds and tests the docker images"
inputs:
  platform:
    required: false
    description: "defines the target platform containers for this service will run on, using the os[/arch[/variant]] syntax"
    default: 'linux/amd64'
  image:
    required: true
    description: "Image and version (e.g. my/app:8.0-apache)"
  php:
    required: true
    description: "PHP Version"
  distro:
    required: true
    description: "PHP Distribution (e.g. apache, fpm, cli)"
  os:
    required: true
    description: "Debian Operating System Distribution"
runs:
  using: "composite"
  steps:
    - name: Build Images
      env:
        IMAGE_TAG: ${{ inputs.php }}-${{ inputs.distro }}-${{ inputs.os }}-test
        BUILD_DIR: src/${{ inputs.php }}/${{ inputs.distro }}/${{ inputs.os }}
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: docker-compose build sut
      shell: bash

    - name: Get Composer Cache Directory
      id: composer-data
      run: |
        echo "dir=$(composer config --global data-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Framework Version
      id: framework
      run : |
        if [[ "${{ inputs.php }}" == "8.2" ]]; then echo "version=5@dev" >> $GITHUB_OUTPUT ; else echo "version=4" >> $GITHUB_OUTPUT; fi
      shell: bash

    - name: Cache Composer Downloads
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-data.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ steps.framework.outputs.version }}-${{ inputs.php }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ steps.framework.outputs.version }}

    - name: Create Silverstripe ${{ steps.framework.outputs.version }} test project
      env:
        COMPOSER_HOME: ${{ steps.composer-data.outputs.dir }}
      run: |
        docker-compose run --rm composer config -g platform.php ${{ inputs.php }}
        docker-compose run --rm composer config -g platform.ext-intl 1
        docker-compose run --rm composer config -g --no-interaction allow-plugins.composer/installers true
        docker-compose run --rm composer create-project --no-interaction --no-dev silverstripe/installer . ^${{ steps.framework.outputs.version }}
      shell: bash

    - name: Run tests
      env:
        IMAGE_TAG: ${{ inputs.php }}-${{ inputs.distro }}-${{ inputs.os }}
        IMAGE: ${{ inputs.image }}
        PLATFORM: ${{ inputs.platform }}
        DOCKER_BUILDKIT: 1
        COMPOSE_DOCKER_CLI_BUILD: 1
      run: docker-compose run sut
      shell: bash

    - name: The job has failed
      if: ${{ failure() }}
      run: |
        docker-compose logs
      shell: bash
  