name: Build and Push multi-arch
on:
  pull_request:

# on:
#   push:
#     branches:
#       - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, buster, alpine]
        php: ['7.4', '8.0', '8.1']
        distro: [apache, fpm, cli]
        exclude:
          - os: alpine
            distro: apache
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: src/${{ matrix.php }}/${{ matrix.distro }}/${{ matrix.os }}
          platforms: linux/amd64,linux/arm64
          push: false
          tags: brettt89/silverstripe-web:${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.os }}
