name: GitHub CI
on:
  pull_request:
    # Pattern matched against changes to src/, test/ and .github/
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
  push:
    branches:
      - master
jobs:
  test:
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, buster, alpine]
        php: ['8.0', '8.1', '8.2']
        framework: [4, 5@dev]
        distro: [apache, fpm, cli]
        exclude:
          - os: alpine
            distro: apache
          - php: 8.0
            framework: 5@dev
          # Once PHP 5 has been released, these need to be updated to 5
          - php: 8.1
            framework: 5@dev
          - php: 8.2
            framework: 4
        include:
          - os: bullseye
            additional_distro: true
          - os: bullseye
            distro: apache
            additional_php: true
          - os: bullseye
            php: 8.1
            distro: apache
            latest: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            brettt89/silverstripe-web
          tags: |
            type=raw,value=${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.os }}
            type=raw,value=${{ matrix.php }}-${{ matrix.distro }},enable=${{ matrix.additional_distro || false }}
            type=raw,value=${{ matrix.php }},enable=${{ matrix.additional_php || false }}
            type=raw,value=latest,enable=${{ matrix.latest || false }}
            type=semver,pattern=${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.os }}-{{version}}
            type=semver,pattern=${{ matrix.php }}-${{ matrix.distro }}-${{ matrix.os }}-{{major}}.{{minor}}

      - id: test
        uses: ./.github/actions/build-test
        with:
          php: ${{ matrix.php }}
          distro: ${{ matrix.distro }}
          os: ${{ matrix.os }}
          framework: ${{ matrix.framework }}