name: GitHub CI
on:
  pull_request:
    # Pattern matched against changes to src/, test/ and .github/
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'
  push:
    branches:
      - master
jobs:
  test:
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, buster, alpine]
        php: ['8.0', '8.1', '8.2']
        framework: [4, 5@dev]
        distro: [apache, fpm, cli]
        exclude:
          - os: alpine
            distro: apache
          - php: 8.0
            framework: 5@dev
          # Once PHP 5 has been released, these need to be updated to 5
          - php: 8.1
            framework: 5@dev
          - php: 8.2
            framework: 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - id: test
        uses: ./.github/actions/build-test
        with:
          php: ${{ matrix.php }}
          distro: ${{ matrix.distro }}
          os: ${{ matrix.os }}
          framework: ${{ matrix.framework }}